### ISSUE TITLE
Stop header map expands when collapsing service alerts

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-ios#437]
See video for details 

https://user-images.githubusercontent.com/2254/127946861-2883dd43-5ecf-4460-a5e7-ea213f8d7e8c.MP4

**Comment by cathy810218** [comment]
Hi Aaron and Alan! 
I’m interested in tackling this issue but when I tried to repro- I’m unable to see the map expand. Wondering if this is still an issue? Thank you!

https://user-images.githubusercontent.com/12047881/141947687-9d9114b0-aee6-47c3-8971-a925558974d7.MP4

**Comment by ualch9** [comment]
thanks, cathy! take a look at the attached video. I'm using an iPhone 13 Pro running iOS 15.1. this problem might be platform dependent.

let me know if you'd like more info

https://user-images.githubusercontent.com/22162410/141948146-b01b253d-eac5-45cc-b9a7-0bf4ed71a17c.MOV

**Comment by cathy810218** [comment]
Hi Alan! Yeah I’m using iPhone 11 Pro with iOS 15.1. 

I will try it on the simulator to see if I can repro it with iphone13 and let you know if I need more info! Thanks much!

**Comment by cathy810218** [comment]
Hey Alan, I just found out that what you've shown is reproducible when tapping on "load more" (multiple times).
It seems to be related to how many rows are shown in the Arrivals and Departures. (for example, on load more, if there are 4 rows, the stop header map will collapse)

But I am not sure if that is the issue as it seems to be a little different than the initial issue that is described/shown in Aaron's video where the Stop Header map expands when tapping on Service Alert.

Would you be able to repro that behavior on your end? 
Thank you :)

https://user-images.githubusercontent.com/12047881/142753119-bda0305d-85a1-4b17-b0fa-f001a7b84df0.MP4

**Comment by ualch9** [comment]
@cathy810218 my mistake, i should've clarified that the bug has evolved.
on ios 15, the stop header defaults to being expanded until the view re-layouts.

Actual behavior (see video):
1. View Stop 620
2. Observe expanded stop header height
3. Scroll down and load more trips
4. Scroll back to top of page
5. Observe standard stop header height
6. end.

Expected behavior:
1. View Stop 620
2. Observe standard stop header height.
3. end.

https://user-images.githubusercontent.com/22162410/142898604-6672c2b5-e33b-4ecc-812b-607dd9d1a376.mov
