### ISSUE TITLE
OBA no longer provides ETA predictions for future stops on the same route. 

### ISSUE THREAD

**Issue by skeffs** [OneBusAway/onebusaway-ios#583]
This bug is new as of the week of 12 Dec. 2021. I’m on iOS 14.8.1 for context.

When I’m in the app and I try to look at details for when a specific bus will arrive at another stop further along the route, I receive the following error message: “The data couldn’t be read because it is missing.”

I use this function quite regularly, and so this is a frustrating development. Please fix at your earliest convenience. Thank you. 
 
![74BB9F42-820C-4076-83B3-2C870A4F9030](https://user-images.githubusercontent.com/96150803/146089688-28da71ca-9525-434e-88b1-b72da6e32f46.png)

**Comment by ualch9** [comment]
@skeffs We are having intermittent data outages with Sound Transit and we are working with them to get this resolved. Once it’s resolved, it should be automatically fixed in the iPhone app. 

In the meantime, the web app is functioning and can be accessed via pugetsound.onebusaway.org. 

~~

I am closing this issue, since this is a data issue related to the transit agency, not something wrong with the app itself.
